version: '3.8'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=1234
    - POSTGRES_USER=isaque
    - POSTGRES_DB=money_wise